import type { Metadata } from 'next'
import Navigation from '@/components/ui/Navigation/Navigation'
import localFont from 'next/font/local'
import Footer from '@/components/Footer/Footer'
import './globals.css'

const geistSans = localFont({
	src: './fonts/GeneralSans.woff',
	variable: '--font-geist-sans',
	weight: '100 400 500 600 900',
})

const Coolvetica = localFont({
	src: './fonts/Coolvetica.ttf',
	variable: '--font-geist-mono',
	weight: '400 500 600 700 800',
})

export const metadata: Metadata = {
	title: 'Solarnova',

	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={`${geistSans.variable}  ${Coolvetica.variable} antialiased`}>
				<Navigation />
				{children}
				<Footer />
			</body>
		</html>
	)
}
